export const CANONICAL_FIELDS: string[] = [
  "AbleToRecord",
  "AcademicAchievements",
  "AcceptanceAcknowledgment",
  "Accommodations",
  "AccommodationsDescribe",
  "Accurate",
  "AdditionalInfo",
  "AdditionalRank",
  "Additional_Factors",
  "Additional_Factors_Spec",
  "Address1",
  "Address2",
  "AdmissionsTerm",
  "AdmittedViaSubmittable",
  "Agreement",
  "AlternateSetting",
  "AlumniFamilyMemberNames",
  "AnotherDPSCD",
  "AnotherSchool",
  "AnotherSchoolAttend",
  "ApplicantType",
  "ApplicationCount",
  "ApplyingSchool",
  "AppropriatePlacement",
  "Assignment",
  "AssignmentUpdated",
  "AttendDuration",
  "AttendMSAC",
  "AuditionArea",
  "ChryslerExpectations",
  "City",
  "Commmunication",
  "Communication",
  "Complete504",
  "CompleteDocumentsResponsibility",
  "CompleteIEP",
  "CompleteIEP504",
  "Completion",
  "ConflictOfInterest",
  "ContactPerson",
  "ContactPersonEmail",
  "ConvincingCandidate",
  "Country",
  "CreativeWritingExperience",
  "CumulativeGPA",
  "CurrentExamSchool",
  "CurrentGrade",
  "CurrentRecentSchool",
  "CurrentReportCards",
  "CurrentSchool",
  "CurrentlyEnrolled",
  "DOB",
  "DPSCD",
  "DPSCDEmployee",
  "DPSCDEmployeeID",
  "DPSCDEmployeeName",
  "DPSCDGPA",
  "DPSCDSchool",
  "DPSCDWithOOD",
  "DPSCD_Bonus",
  "DSA_Aspirations",
  "Decision",
  "DecisionIsFinal",
  "DeclineNotes",
  "Decline_Reason",
  "Decline_Specifics",
  "DiscrepancyDetails",
  "Dismissed",
  "DismissedReturn",
  "DismissedSchool",
  "DismissedYear",
  "DuplicateApplications",
  "ELL",
  "ELLStatement",
  "ELLTeacherRef",
  "ELLTeacherRefAddress",
  "ELLTeacherRefEmail",
  "ELLTeacherRefName",
  "ELLTeacherRefPhone",
  "EdisonAltGradeOption",
  "EdmonsonAttendingCount",
  "EdmonsonSiblingNames",
  "Elaboration",
  "Eligibility28",
  "EligibleDesiredGrade",
  "EligibleK",
  "EligiblePreK",
  "Email",
  "Essay",
  "Essay_Scored",
  "Evidence",
  "ExamConfirmation",
  "ExamDate",
  "Exam_Score",
  "ExperienceDemonstrated",
  "ExperienceDescription",
  "ExperienceHow",
  "ExperienceReviewDiscrepancy",
  "FLICS",
  "FLICSExpectations",
  "FLICSPreK",
  "Factors",
  "FallTestDPSCD",
  "FamilyMembersDSAAlumni",
  "FifthChoiceSchool",
  "FinalDecision",
  "FirstChoiceSchool",
  "FirstName",
  "FollowUpNotes",
  "FollowUpPerson",
  "FollowUpWith",
  "FormsOfWriting",
  "FourthChoiceSchool",
  "FullName",
  "GPA",
  "GPA_Bonus",
  "GPA_Multiplier",
  "GPA_Recorded",
  "GPA_Score",
  "Gender",
  "GoodAcademicStanding",
  "GoodAttendance",
  "GoodBehaviorStanding",
  "Gr2Up",
  "Grad_Progress",
  "Grade",
  "GradeEntering",
  "GradeRange",
  "HSPT_Taken",
  "HowToProceed",
  "IEPor504",
  "IEPorNPSPor504",
  "InPersonAuditionAcknowledgment",
  "InstrumentalMusicExperience",
  "Interests",
  "Interview",
  "InterviewWhen",
  "InterviewWho",
  "Issue",
  "IssueApplication",
  "IssueDescribe",
  "IssueIEP",
  "IssueIEP504",
  "Issues",
  "IssuesOther",
  "LNGE",
  "LN_Pctl",
  "Language",
  "LanguageFirstChoice",
  "LanguageProficient",
  "LanguageSecondChoice",
  "LanguageStatement",
  "LanguageThirdChoice",
  "LastName",
  "LastYearReportCards",
  "LetterPreference",
  "MG6th",
  "MG_Bonus",
  "MG_Catchment",
  "MLLAccommodations",
  "MLLCategory",
  "MTGE",
  "MT_Pctl",
  "MarygroveAttendingCount",
  "MarygroveSelected",
  "MarygroveSiblingNames",
  "MissingInfo",
  "MontEligibilityFlag",
  "MontMGSelected",
  "MontSiblingID",
  "MontSiblingSchool",
  "MontessoriDocumentation",
  "MultipleSports",
  "NonArtsSubjects",
  "NonDPSCDAttend",
  "NonDPSCDSchool",
  "NonDPSCDSchoolAttendance",
  "Notes",
  "NotesInternal",
  "NotesLanguage",
  "OODSchool",
  "Observations",
  "Observations504",
  "OpenForEditing",
  "OptInConsent",
  "Organization",
  "OtherLanguage",
  "OtherLanguageSelection",
  "OtherSchool",
  "OtherSchoolLocation",
  "PalmerAttendingCount",
  "PalmerSiblingNames",
  "ParentEmail",
  "ParentEmailAlt",
  "ParentFirstName",
  "ParentGuardianSignature",
  "ParentLastName",
  "ParentPhone",
  "ParentPhone2",
  "ParentPhoneAlt",
  "Phone",
  "PowerSchoolGPA",
  "PreK",
  "PreviousMontessori",
  "PreviousMontessoriExperience",
  "PreviousMontessoriExperienceEvidence",
  "PreviousMontessoriSchool",
  "PreviousMontessoriSchoolPhone",
  "PrimaryEligibiliy",
  "PrimaryInstrument",
  "Program",
  "RDGE",
  "RD_Pctl",
  "Reason",
  "ReasonForLeaving",
  "Ref1Details",
  "Ref1Email",
  "Ref1Name",
  "Ref1Phone",
  "Ref1Relationship",
  "Ref2Details",
  "Ref2Email",
  "Ref2Name",
  "Ref2Phone",
  "Ref2Relationship",
  "Ref3Details",
  "Ref3Email",
  "Ref3Name",
  "Ref3Phone",
  "Ref3Relationship",
  "RefDetails",
  "RefOne",
  "RefTwo",
  "RegisterForExam1",
  "RegisterForExam2",
  "RequirementsSatisfied",
  "RespondsAppropriately",
  "ReturnAfterDismissal",
  "ReturnSchool",
  "ReturnSchoolAttended",
  "ReturnSchoolLeftReason",
  "ReturnSchoolStop",
  "ReturnSiblingAttending",
  "ReturnSiblingName",
  "ReviewType",
  "Round",
  "SCGE",
  "SC_Pctl",
  "SEMCOG",
  "School",
  "SchoolApplying",
  "Schools",
  "SecondChoiceSchool",
  "SecondaryInstrument",
  "Semesters",
  "SiblingApplicantNames",
  "SiblingApplying28",
  "SiblingApplyingTogether",
  "SiblingApplyingTogetherNames",
  "SiblingAttending",
  "SiblingAttendingEdmonson",
  "SiblingAttendingNames",
  "SiblingAttendingPalmer",
  "SiblingAttendingSchools",
  "SiblingDescribe",
  "SiblingID",
  "SiblingID2",
  "SiblingIDs",
  "SiblingInfo",
  "SiblingNames",
  "SiblingPreference",
  "SiblingReviewDiscrepancy",
  "SiblingSchool",
  "SiblingSchool2",
  "SiblingSchools",
  "SiblingSubmissionIDs",
  "SiblingsAttendDSA",
  "SiblingsDescribe",
  "SignatureParent",
  "SignatureStudent",
  "SingingExperience",
  "SingleAcceptance",
  "SocialJustice",
  "SpeechEligible",
  "SpokeToFamily",
  "SpokeToSchool",
  "Sports",
  "StandardizedTestScores",
  "State",
  "StatementGrade12",
  "StudentNumber",
  "StudentNumberRe",
  "SubmittableLink",
  "TeacherSupport1",
  "TeacherSupport2",
  "TestScores",
  "ThirdChoiceSchool",
  "Total_App_Score",
  "Total_MG_Score",
  "TranscriptProvided",
  "TransferWindow",
  "UpdateLog",
  "Upload504",
  "UploadAdditionalSchool",
  "UploadGr6",
  "UploadGr7",
  "UploadGr8",
  "UploadIEP",
  "UploadNonDPSCD",
  "UploadReportCard",
  "UploadSpeech",
  "UploadTranscript",
  "UploadWIDA",
  "VocalRange",
  "WIDALowQualified",
  "WIDASubmitted",
  "Zip",
  "applyingMontessori",
  "collaborationSessionId",
  "completedAt",
  "createdAt",
  "createdBy",
  "deadline",
  "documentation1",
  "documentation2",
  "enrollmentNotes",
  "enrollmentStatus",
  "entryId",
  "entryVersionId",
  "experienceMontessori",
  "formId",
  "formResponseId",
  "formType",
  "gradeEntering",
  "hasBeenOpenedForEditing",
  "isAssigned",
  "isCompleted",
  "isStrictDeadline",
  "missing",
  "openedForEditingAt",
  "payment",
  "projectId",
  "reviewerId",
  "score",
  "siblingPriority",
  "stageId",
  "status",
  "submissionFormId",
  "submissionId",
  "userId",
]

export const LEGACY_FIELD_MAP: Record<string, string> = {
  "submissionId": "submissionId",
  "projectId": "projectId",
  "stageId": "stageId",
  "userId": "userId",
  "score": "score",
  "formType": "formType",
  "formResponseId": "formResponseId",
  "entryId": "entryId",
  "formId": "formId",
  "status": "status",
  "createdBy": "createdBy",
  "createdAt": "createdAt",
  "isCompleted": "isCompleted",
  "completedAt": "completedAt",
  "entryVersionId": "entryVersionId",
  "collaborationSessionId": "collaborationSessionId",
  "openedForEditingAt": "openedForEditingAt",
  "reviewerId": "reviewerId",
  "isAssigned": "isAssigned",
  "paymentReceipt.paymentLines": "payment",
  "Student's Full Name": "FullName",
  "firstName1": "FirstName",
  "lastName1": "LastName",
  "Communication about your application": "Commmunication",
  "I acknowledge that, if accepted, I will receive only one acceptance letter. I will be accepted to my highest-ranked school that extends an admission offer. I understand that I may file a petition if I do not get accepted to my desired school.": "SingleAcceptance",
  "firstName2": "ParentFirstName",
  "lastName2": "ParentLastName",
  "Parent/Guardian Email Address": "ParentEmail",
  "Parent/Guardian Phone Number": "ParentPhone",
  "Parent/Guardian Phone Number - 2 (OPTIONAL)": "ParentPhone2",
  "address1": "Address1",
  "address2": "Address2",
  "city": "City",
  "region": "State",
  "postalCode": "Zip",
  "country": "Country",
  "Student's Date of Birth": "DOB",
  "Student's Email Address": "Email",
  "Student's Phone Number": "Phone",
  "Student's Gender": "Gender",
  "Does the student currently attend a DPSCD (Detroit Public Schools Community District) school?": "DPSCD",
  "Please review the guiding questions and type your essay into the box.": "Essay",
  "First-Choice School": "FirstChoiceSchool",
  "Second-Choice School": "SecondChoiceSchool",
  "Third-Choice School": "ThirdChoiceSchool",
  "Fourth-Choice School": "FourthChoiceSchool",
  "Fifth-Choice School": "FifthChoiceSchool",
  "Would you like to select/rank additional schools?": "AdditionalRank",
  "Reference Person #1 - Name": "Ref1Name",
  "Reference Person # 1 - Phone": "Ref1Phone",
  "Reference Person #1 - Email Address": "Ref1Email",
  "Reference # 1 - Relationship to Applicant": "Ref1Relationship",
  "Reference #2 - Name": "Ref2Name",
  "Reference Person # 2 - Phone": "Ref2Phone",
  "Reference #2 - Email Address": "Ref2Email",
  "Reference #2 - Relationship to Applicant": "Ref2Relationship",
  "Reference #3 - Name": "Ref3Name",
  "Reference #3 - Phone": "Ref3Phone",
  "Reference #3 - Email Address": "Ref3Email",
  "Reference #3 - Relationship to Applicant": "Ref3Relationship",
  "Additional Interests and Extra-Curricular Activities": "Interests",
  "I understand that DPSCD requires two full years of academic records as part of the exam high school admission process. I give my consent for my student's middle school grades to be provided to DPSCD if my school has opted into supplying records directly to DPSCD. Otherwise, I acknowledge that I am personally responsible for uploading all requested documents to my application, if applicable.": "OptInConsent",
  "Student Electronic Signature (Enter FIRST Name and LAST Name)": "SignatureStudent",
  "Parent Electronic Signature (Enter FIRST Name and LAST Name)": "SignatureParent",
  "Does the student attend a school in Southeast Michigan?": "SEMCOG",
  "Does the student have an IEP, NPSP or 504 Plan?": "IEPorNPSPor504",
  "Is the student a native speaker of a language other than English?": "ELL",
  "Please select an exam date:": "ExamDate",
  "Current School": "OODSchool",
  "What sport(s) do you play?": "Sports",
  "DPSCD school the student currently attends.": "DPSCDSchool",
  "Student's DPSCD Student ID number": "StudentNumber",
  "Re-enter the student's DPSCD Student ID number": "StudentNumberRe",
  "Does the student have an IEP or 504 Plan?": "IEPor504",
  "Did the student attend a Non-DPSCD school at any point in the last two school years?": "NonDPSCDAttend",
  "Did your student attend another school between 2021 and 2023?": "AnotherSchoolAttend",
  "Was the other school a DPSCD school?": "AnotherDPSCD",
  "What is the name of the other school your student attended between 2021 and 2023?": "AnotherSchool",
  "Current School (Out of Area)": "OtherSchool",
  "Where is the school located?": "OtherSchoolLocation",
  "Please provide more detail on the reference's relation to the applicant.": "RefDetails",
  "What language does the student speak?": "Language",
  "Please select the statement that best describes the student.": "ELLStatement",
  "Did the student take the High School Placement Test in their DPSCD school last fall?": "FallTestDPSCD",
  "Name(s) of the Non-DPSCD school(s) the student attended during the last two school years": "NonDPSCDSchool",
  "If accepted, please indicate the type of letter you would like to receive": "LetterPreference",
  "Please enter the name of a teacher, counselor or administrator at the student's school who can speak about the ELL/MLL services the student is receiving.": "ELLTeacherRef",
  "Please enter the school contact's phone number.": "ELLTeacherRefPhone",
  "Please enter the school contact's email address.": "ELLTeacherRefAddress",
  "Did your student attend another school between 2022 and 2024?": "AnotherSchoolAttend",
  "What is the name of the other school your student attended between 2022 and 2024?": "AnotherSchool",
  "Please select the area for which you would like to audition/interview.": "AuditionArea",
  "I have read and agree to the statements listed below.": "Agreement",
  "I acknowledge that the decision on this application is final. There is no appeal or petition. I acknowledge that, if accepted, I will receive only one acceptance letter. I will be accepted to my highest-ranked school that extends an admission offer.": "DecisionIsFinal",
  "Grade Entering for the 2025-26 School Year": "GradeEntering",
  "Is the student a native speaker of a language other than English? ": "OtherLanguage",
  "Current/Most Recent School": "CurrentRecentSchool",
  "How long did the student attend that school?": "AttendDuration",
  "Reference Person #1 - Phone": "Ref1Phone",
  "Reference Person #2 - Name": "Ref2Name",
  "Reference Person #2 - Phone": "Ref2Phone",
  "Reference Person #2 - Email Address": "Ref2Email",
  "Reference # 2 - Relationship to Applicant": "Ref2Relationship",
  "Reference Person #3 - Name": "Ref3Name",
  "Reference Person #3 - Phone": "Ref3Phone",
  "Reference Person #3 - Email Address": "Ref3Email",
  "Reference # 3 - Relationship to Applicant": "Ref3Relationship",
  "Please select the statement that best describes the student.  ": "LanguageStatement",
  "Please enter the name of a teacher, counselor or administrator at the student's school who can speak about the ELL/MLL services the student is receiving. ": "ELLTeacherRefName",
  "Please enter the school contact's email address. ": "ELLTeacherRefEmail",
  "Did your student attend another school in 6th grade or 7th grade?": "AnotherSchoolAttend",
  "What is the name of the other school your student attended?": "AnotherSchool",
  "DPSCD school the student currently attends": "DPSCDSchool",
  "Upload 8th Grade Report Card - 2025-26 School Year": "UploadGr8",
  "Upload 7th Grade Transcript or Report Cards - 2024-25 School Year": "UploadGr7",
  "Upload 6th Grade Transcript or Report Cards - 2023-24 School": "UploadGr6",
  "Upload Student's Current IEP/NPSP.": "UploadIEP",
  "Upload Transcripts or Report Cards From Additional School(s)": "UploadAdditionalSchool",
  "Upload Student's Current 504 Plan.": "Upload504",
  "Upload Academic Records from Non-DPSCD School(s)": "UploadNonDPSCD",
  "Upload student's most recent WIDA scores": "UploadWIDA",
  "I acknowledge that the decision on this application is final. There is no appeal or petition.": "FinalDecision",
  "I acknowledge that, if accepted, I will receive only an acceptance letter to DSA. I am only being considered for Detroit School of Arts by completing this application. I may apply to other Application Schools and Exam High Schools by using different applications.": "AcceptanceAcknowledgment",
  "Grade Entering for the 2026-27 School Year (Next Year)": "GradeEntering",
  "Does the student currently attend a DPSCD school?": "DPSCD",
  "Does the student have any siblings who currently attend DSA?": "SiblingsAttendDSA",
  "Does the student have any family members who are DSA alumni?": "FamilyMembersDSAAlumni",
  "DSA is a school for the gifted and talented, which means we strive for excellence in arts and academics. Please describe your academic achievements. ": "AcademicAchievements",
  "What do you hope Detroit School of Arts will help you achieve?": "DSA_Aspirations",
  "Outside of the arts, which subjects in school interest you the most? Why?": "NonArtsSubjects",
  "Duplicate applications are prohibited": "DuplicateApplications",
  "Does the student attend one of the following DPSCD Middle School Arts Conservatories?": "AttendMSAC",
  "Select the DPSCD school the student currently attends.": "DPSCDSchool",
  "Please enter the DPSCD Student ID": "StudentNumber",
  "Did the student attend a Non-DPSCD school at any point in the 2023-24 or 2024-25 school years?": "NonDPSCDSchoolAttendance",
  "Please enter alumni family member name(s) here.": "AlumniFamilyMemberNames",
  "What creative writing experience do you have? Please explain.": "CreativeWritingExperience",
  "What forms of writing have you focused on in the past?": "FormsOfWriting",
  "I acknowledge that my arts discipline requires an in-person audition. I have selected my audition date and time at the link provided above. ": "InPersonAuditionAcknowledgment",
  "What singing experience do you have? ": "SingingExperience",
  "What is your vocal range?": "VocalRange",
  "What instrumental music experience do you have?": "InstrumentalMusicExperience",
  "What is your primary instrument?": "PrimaryInstrument",
  "What is your secondary instrument?": "SecondaryInstrument",
  "I acknowledge that, if accepted, I will receive only one acceptance letter. I will be accepted to my highest-ranked school that extends an admission offer. I understand that I may not be accepted to my highest-ranked school.": "SingleAcceptance",
  "When are you seeking admission?": "AdmissionsTerm",
  "Does the student currently attend a DPSCD (Detroit Public Schools Community District) high school?": "DPSCD",
  "Which of the following statements best describes the student?": "ApplicantType",
  "Please review the guiding questions below and type your essay into the box.": "Essay",
  "Please tell us what Social Justice means to you.": "SocialJustice",
  "Reference Person #1 - Relationship to Applicant": "Ref1Relationship",
  "Please provide more detail on the reference's (#1) relation to the applicant": "Ref1Details",
  "Reference Person #2 - Relationship to Applicant": "Ref2Relationship",
  "Please provide more detail on the reference's (#2) relation to the applicant": "Ref2Details",
  "Reference Person #3 - Relationship to Applicant": "Ref3Relationship",
  "Please provide more detail on the reference's (#3) relation to the applicant": "Ref3Details",
  "Please select all activities in which you have participated or have an interest.": "Interests",
  "I understand that DPSCD requires two full years of academic records as part of the exam high school admission process. I give my consent for my student's middle school grades to be provided to DPSCD if my school has opted into supplying records directly to DPSCD. Otherwise I acknowledge that I am personally responsible for uploading all requested documents to my application if applicable.": "OptInConsent",
  "Please select an exam date": "ExamDate",
  "What is the name of the school the student currently attends?": "OODSchool",
  "Do you currently play on one or more sports teams at your current school?": "MultipleSports",
  "Did the student attend a Non-DPSCD school at any point in the two previous (2022-23 or 2023-24) school years?": "NonDPSCDAttend",
  "Select the school to which you want to return": "ReturnSchool",
  "When did the student attend the school?": "ReturnSchoolAttended",
  "Why did the student stop attending the school?": "ReturnSchoolStop",
  "Does the applicant currently have any siblings who attend the school(s) to which they are applying?": "SiblingAttending",
  "Does the applicant have any siblings at the school to which they are applying?": "ReturnSiblingAttending",
  "Name(s) of sibling(s) who currently attend(s) the school.": "ReturnSiblingName",
  "Name(s) of sibling(s) attending exam high school(s).": "SiblingNames",
  "School(s) the sibling(s) attend(s).": "SiblingSchool",
  "Please provide the reason for leaving the Exam High School you previously attended.": "ReasonForLeaving",
  "Which of the following statements applies to the student who will enter 12th grade? Select all that apply.": "StatementGrade12",
  "Communication about this application": "Communication",
  "Grade Entering for the 2026-27 School Year": "GradeEntering",
  "When is the student seeking admission?": "AdmissionsTerm",
  "I understand that DPSCD requires two full years of academic records as part of the exam high school admission process. I acknowledge that I am personally responsible for uploading all requested documents to my application, if applicable.": "CompleteDocumentsResponsibility",
  "Did the student attend a Non-DPSCD school at any point in the two previous (2023-24 or 2024-25) school years?": "AnotherSchoolAttend",
  "Select the school to which the student wants to return": "ReturnSchool",
  "Please review the guiding questions below and type the student-authored essay into the box.": "Essay",
  "Please provide the reason for leaving the Exam High School that was previously attended.": "ReturnSchoolLeftReason",
  "Upload Student's Transcript showing at least two years of grades": "UploadTranscript",
  "Upload Most Recent Report Card - Current School Year": "UploadReportCard",
  "Upload the Student's Transcript from their Non-DPSCD School": "UploadNonDPSCD",
  "Upload the Student's IEP or NPSP": "UploadIEP",
  "Upload the Student's 504 Plan": "Upload504",
  "When are you seeking to transfer to another examination high school?": "TransferWindow",
  "Grade entering for 2025-26 School year": "GradeEntering",
  "Was the student dismissed from an exam high school they previously attended? ": "Dismissed",
  "Which exam high school does the student currently attend?": "CurrentExamSchool",
  "Which school is the student applying to attend?": "FirstChoiceSchool",
  "Parent/Guardian Phone Number - 2 (Optional)": "ParentPhone2",
  "Does the applicant currently have one or more siblings at the school to which they want to transfer?": "SiblingAttending",
  "Does the applicant currently play on one or more sports teams at their current school?": "Sports",
  "Why are you seeking a transfer and why should the school accept you?": "Essay",
  "Did the student attend a Non-DPSCD school at any point in the past two school years?": "NonDPSCDAttend",
  "Name(s) of sibling(s) at school identified.": "SiblingNames",
  "Is the student applying to return to the school they were dismissed from? ": "DismissedReturn",
  "What school year was the student dismissed?": "DismissedYear",
  "What school was the student dismissed from?": "DismissedSchool",
  "Grade entering for 2026-27 School year": "GradeEntering",
  "Is the student a current DPSCD student who has provided OOD grades?": "DPSCDWithOOD",
  "Are you able to record a Cumulative GPA?": "AbleToRecord",
  "Review Notes": "Notes",
  "Record Cumulative GPA": "CumulativeGPA",
  "What are the issues with this submission? (Select all that apply)": "Issues",
  "Please describe the other issue(s) with the submission.": "IssuesOther",
  "How many semesters of information were provided?": "Semesters",
  "Please make additional notes so that we may follow up on this issue.": "Issue",
  "How much information was provided?": "Semesters",
  "I have reviewed the Conflict of Interest Statement and affirm that I do not have a conflict of interest": "ConflictOfInterest",
  "Appropriately responds to questions": "RespondsAppropriately",
  "Presents themselves as a convincing candidate": "ConvincingCandidate",
  "Organization, structure, grammar": "Organization",
  "submissionFormId": "submissionFormId",
  "deadline": "deadline",
  "isStrictDeadline": "isStrictDeadline",
  "hasBeenOpenedForEditing": "hasBeenOpenedForEditing",
  "What is your first-choice school for the petition?": "FirstChoiceSchool",
  "What is your second-choice school for the petition?": "SecondChoiceSchool",
  "What is your third-choice school for the petition?": "ThirdChoiceSchool",
  "What is your fourth-choice school for the petition?": "FourthChoiceSchool",
  "What is your fifth-choice school for the petition?": "FifthChoiceSchool",
  "Essay Question: Why are  you a strong candidate for the school(s) you have selected?": "Essay",
  "How will you submit your first reference?": "RefOne",
  "How will you submit your second reference?": "RefTwo",
  "Please indicate what you plan to provide as a third piece of evidence in support of your petition": "Evidence",
  "Parent/Guardian Signature": "ParentGuardianSignature",
  "Did you select The School at Marygrove as one of your choices in your initial application? ": "MarygroveSelected",
  "Please tell us what Social Justice means to you. ": "SocialJustice",
  "What grade will your child enter this fall?": "GradeEntering",
  "Select the school(s) you would like to consider your appeal application.": "Schools",
  "Does the student have a sibling at the school(s) to which they are appealing?": "SiblingAttending",
  "Please upload report cards from the current school year (2025-26)": "CurrentReportCards",
  "Please upload report cards from last year (2024-25)": "LastYearReportCards",
  "Please upload recent Standardized Test Scores": "StandardizedTestScores",
  "Did you select FLICS on your original application?": "FLICS",
  "Please list sibling(s) name and school": "SiblingInfo",
  "Please select the language in which your child is proficient.": "LanguageProficient",
  "Please select your first-choice language": "LanguageFirstChoice",
  "Please select your second-choice language": "LanguageSecondChoice",
  "Please select your third-choice language": "LanguageThirdChoice",
  "First Choice": "FirstChoiceSchool",
  "Second Choice": "SecondChoiceSchool",
  "Third Choice": "ThirdChoiceSchool",
  "Did you select FLICS in your original application?": "FLICS",
  "What is your decision regarding this student's admission?": "Decision",
  "Please select all factors that contributed to your decision": "Factors",
  "What additional reason factored into the decision to decline the applicant? Please be specific.": "Additional_Factors_Spec",
  "What additional reason factored into the decision to accept the applicant?": "Additional_Factors",
  "School Name": "School",
  "Teacher Recommendation #1 Supports Admission to Exam School": "TeacherSupport1",
  "Teacher Recommendation #2 Supports Admission to Exam School": "TeacherSupport2",
  "Admission decision": "Decision",
  "You chose to decline this student. Please make additional notes regarding your reasoning here.": "DeclineNotes",
  "What additional reason factored into the decision to accept/decline the applicant?": "Additional_Factors",
  "Did the applicant submit a complete IEP or other ESE document for review?": "CompleteIEP",
  "What was the issue with the IEP submitted?": "IssueIEP",
  "Optional: Please describe any other IEP observations we should be aware of.": "Observations",
  "Please describe the alternate setting needed": "AlternateSetting",
  "Based on the IEP, is the school an appropriate placement if the student is accepted?": "AppropriatePlacement",
  "Please select the accommodations that should be provided to this student": "Accommodations",
  "What is the Student's Program?": "Program",
  "What is the Student's Primary Eligibility?": "PrimaryEligibiliy",
  "Please describe the accommodation(s) needed": "AccommodationsDescribe",
  "Did you open the application for editing, send the message and add the 00-Application Opened label?": "OpenForEditing",
  "Please describe the issue with the application": "IssueApplication",
  "Please explain the reason for your response": "Reason",
  "Did the applicant submit a complete IEP for review?": "CompleteIEP",
  "Based on the IEP, is an exam high school an appropriate placement if the student is accepted?": "AppropriatePlacement",
  "Please select all the accommodations that should be provided to this student": "Accommodations",
  "Did the applicant submit a complete IEP/ 504 for review?": "CompleteIEP504",
  "What was the issue with the IEP/ 504 submitted?": "IssueIEP504",
  "Please describe the issue with the document uploaded.": "IssueDescribe",
  "Did the applicant submit a complete 504 Plan for review?": "Complete504",
  "Optional: Please describe any other 504 observations we should be aware of.": "Observations504",
  "Please describe the issue with the submitted document": "IssueDescribe",
  "Which statement best describes how Admissions should proceed with this application?": "HowToProceed",
  "Type of Review": "ReviewType",
  "Is the student eligible for speech support for Brigance?": "SpeechEligible",
  "Optional Notes": "Notes",
  "Which Grade Range Is the Student Entering?": "GradeRange",
  "Which option applies to the student?": "MLLCategory",
  "Optional: Please describe any other ELL/MLL observations we should be aware of.": "Observations",
  "Did you speak to a family member?": "SpokeToFamily",
  "Does the student qualify for accommodations?": "MLLAccommodations",
  "Please enter notes, including the  language spoken.": "NotesLanguage",
  "Did you speak to a representative from the school?": "SpokeToSchool",
  "Please enter notes. ": "Notes",
  "Did the applicant submit complete WIDA scores for review?": "WIDASubmitted",
  "Did the student score 2.9 or lower on the WIDA?": "WIDALowQualified",
  "Whom did you follow up with?": "FollowUpWith",
  "Based on your follow-up, is the student eligible for accommodations based on WIDA scores?": "MLLAccommodations",
  "Who was the person, and what is their relationship to student?": "FollowUpPerson",
  "Please enter brief notes about your conversation.": "FollowUpNotes",
  "Is the student eligible for accommodations based on WIDA scores?": "MLLAccommodations",
  "Original Assignment": "Assignment",
  "Updated Assignment": "AssignmentUpdated",
  "Assignment Update Log": "UpdateLog",
  "Marygrove Catchment Area": "MG_Catchment",
  "Reading Grade Level Equivalency": "RDGE",
  "Math Grade Level Equivalency": "MTGE",
  "Language Grade Level Equivalency": "LNGE",
  "Science Grade Level Proficiency": "SCGE",
  "Reading Percentile - National / Local": "RD_Pctl",
  "Math Percentile - National / Local": "MT_Pctl",
  "Language Percentile - National / Local": "LN_Pctl",
  "Science Percentile - National / Local": "SC_Pctl",
  "Essay Scored": "Essay_Scored",
  "GPA Recorded": "GPA_Recorded",
  "HSPT Taken": "HSPT_Taken",
  "Total Application Score": "Total_App_Score",
  "Exam Score": "Exam_Score",
  "GPA": "GPA",
  "Essay Score": "Essay",
  "Total Application Score for Marygrove Consideration": "Total_MG_Score",
  "Marygrove Bonus": "MG_Bonus",
  "GPA Bonus": "GPA_Bonus",
  "Partial GPA Multiplier": "GPA_Multiplier",
  "GPA Score": "GPA_Score",
  "Composite Exam Score": "Exam_Score",
  "Update Log": "UpdateLog",
  "Overall GPA": "GPA",
  "GPA in PowerSchool": "PowerSchoolGPA",
  "DPSCD Bonus": "DPSCD_Bonus",
  "Round Processed": "Round",
  "What is your decision regarding the admission of this applicant?": "Decision",
  "Why did you decline this student? (Select all that apply)": "Decline_Reason",
  "Please briefly describe why you declined this student. Be specific.": "Decline_Specifics",
  "Please enter brief notes on your assessment of the student's graduation progress. Include specific concerns.": "Grad_Progress",
  "School Applying To:": "ApplyingSchool",
  "What grade is the student currently in?": "CurrentGrade",
  "What grade is the student applying for?": "GradeEntering",
  "Does the student have a DPSCD cumulative GPA in PowerSchool?": "DPSCDGPA",
  "Was the student admitted via Submittable?": "AdmittedViaSubmittable",
  "Please paste the student's Submittable Link Here": "SubmittableLink",
  "Is the student trying to return after a 2025 dismissal?": "ReturnAfterDismissal",
  "Select the grade you expect your student to enter for the 2024-25 school year": "Grade",
  "Does your student have an IEP or 504 Plan?": "IEPor504",
  "Does your student have a sibling who currently attends any of the schools you selected?": "SiblingAttending",
  "Are you submitting applications for children who are siblings? (Applying Together)": "SiblingApplyingTogether",
  "Does the student have at least one parent who is a full-time DPSCD employee?": "DPSCDEmployee",
  "Does your student currently attend a school in Southeast Michigan?": "SEMCOG",
  "I understand that my child will not be scheduled for the exam unless I submit my application and register for the exam.": "RegisterForExam1",
  "I have read and understand the FLICS scholar and parent expectations": "FLICSExpectations",
  "Is a language other than English spoken in the home?": "OtherLanguage",
  "Language First Choice": "LanguageFirstChoice",
  "Language Second Choice": "LanguageSecondChoice",
  "Language Third Choice": "LanguageThirdChoice",
  "I understand that my child will not be scheduled for the exam unless I submit my application and register for the exam. Instructions on how to register for the exam are provided later in this application.": "RegisterForExam2",
  "Please list the names of all siblings who are seeking admission together, as well as the grades they will enter if admitted.": "SiblingApplyingTogetherNames",
  "Please enter the student's DPSCD Student ID number.": "StudentNumber",
  "Please re-enter the student's DPSCD Student ID number.": "StudentNumberRe",
  "Please select all schools for which you applied and which your student's sibling(s) attend(s)": "SiblingAttendingSchools",
  "Please enter sibling name(s) for verification": "SiblingAttendingNames",
  "Please list the city and state where the school is located.": "OtherSchoolLocation",
  "I have read and understand the Chrysler student and parent expectations": "ChryslerExpectations",
  "Name of parent who is a DPSCD employee": "DPSCDEmployeeName",
  "Parent's DPSCD Employee ID/File Number": "DPSCDEmployeeID",
  "Please select one of the following": "EdisonAltGradeOption",
  "Please select the standardized test scores that you will be submitting on behalf of your student.": "TestScores",
  "Has your student previously attended a Montessori program for at least one year?": "PreviousMontessori",
  "Please describe your student's prior Montessori experience": "PreviousMontessoriExperience",
  "What evidence of prior Montessori experience will you provide?": "PreviousMontessoriExperienceEvidence",
  "What is the name of the school?": "PreviousMontessoriSchool",
  "School phone number": "PreviousMontessoriSchoolPhone",
  "Contact person's name": "ContactPerson",
  "Contact person's email address": "ContactPersonEmail",
  "Please identify all languages other than English that are spoken in the home.": "OtherLanguageSelection",
  "Select the grade you expect your student to enter for the 2026-27 school year": "GradeEntering",
  "Does your student have any of the following?": "IEPor504",
  "Does the student currently attend a DPSCD (Detroit Public Schools Community District) elementary school or PreK program?": "DPSCD",
  "Confirmation of Understanding: Exam Requirements": "ExamConfirmation",
  "Select the DPSCD school/PreK the student currently attends.": "DPSCDSchool",
  "How many applications are you submitting for fall admission at the same school?": "ApplicationCount",
  "What is the name of the school/PreK program the student currently attends?": "CurrentSchool",
  "Please upload a copy of your student's Individualized Education Plan (IEP). Be sure all pages are included.": "UploadIEP",
  "Please upload documentation of your student's speech diagnosis. Be sure all pages are included.": "UploadSpeech",
  "How many of your children already attend The School at Marygrove?": "MarygroveAttendingCount",
  "Please list the names of ALL siblings who currently attend The School at Marygrove": "MarygroveSiblingNames",
  "How many of your children already attend Palmer Park?": "PalmerAttendingCount",
  "Please list the names of ALL siblings who currently attend Palmer Park.": "PalmerSiblingNames",
  "How many of your children already attend Edmonson?": "EdmonsonAttendingCount",
  "Please list the names of ALL siblings who currently attend Edmonson.": "EdmonsonSiblingNames",
  "Alternate Parent/Guardian Phone Number": "ParentPhoneAlt",
  "Alternate Parent/Guardian Email Address": "ParentEmailAlt",
  "Did you select Edmonson, Palmer Park and/or The School at Marygrove": "MontMGSelected",
  "Please select the option that best describes your student's siblings:": "SiblingDescribe",
  "Please upload documentation of your student's prior Montessori education.": "MontessoriDocumentation",
  "Was The School at Marygrove one of your 6th grade choices?": "MG6th",
  "These questions will help us learn more about you as a student, but also as a writer, so put forth your best writing and please work independently.": "Essay",
  "Please upload a copy of your student's full 504 plan. Be sure all pages are included.": "Upload504",
  "Are you interested in enrolling a Pre-K student at FLICS?": "FLICSPreK",
  "Please list the names of all siblings who currently attend Edmonson": "SiblingAttendingEdmonson",
  "Please list the names of all siblings who currently attend Palmer Park.": "SiblingAttendingPalmer",
  "Describe your student's siblings": "SiblingDescribe",
  "Does the student have a parent who is a full-time DPSCD employee?": "DPSCDEmployee",
  "Please double check and re-enter the student's DPSCD Student ID number.": "StudentNumberRe",
  "Select the grade you expect your student to enter for the 2024-5 school year": "Grade",
  "Did you select The School at Marygrove as one of your options?": "MarygroveSelected",
  "Please list the names of ALL siblings who are seeking admission to the same school for fall 2026.": "SiblingApplyingTogetherNames",
  "Please list the names of ALL siblings who currently attend The School at Marygrove.": "MarygroveSiblingNames",
  "Please list the names of ALL siblings who are seeking admission together for fall 2026.": "SiblingApplyingTogetherNames",
  "Please list the names of all siblings who are seeking admission together for fall 2026.": "SiblingApplyingTogetherNames",
  "Please list the names of ALL siblings who currently attend The School at Marygrove.:": "MarygroveSiblingNames",
  "Is your child entering Pre-Kindergarten for the 2024-25 school year?": "PreK",
  "Are you submitting applications for children who are siblings?": "SiblingApplyingTogether",
  "Is the student entering Grade 2 or Higher?": "Gr2Up",
  "Please describe siblings": "SiblingsDescribe",
  "Please add any relevant notes about this review": "Notes",
  "Please list sibling name(s)": "SiblingNames",
  "Which school/program is this student applying for?": "SchoolApplying",
  "How has the applicant demonstrated prior exprience?": "ExperienceHow",
  "Did the applicant's evidence demonstrate eligibility for admission?": "ExperienceDemonstrated",
  "Description of Satisfactory Evidence Provided": "ExperienceDescription",
  "School sibling(s) attend": "SiblingSchool",
  "Enter the Sibling(s)' DPSCD ID": "SiblingID",
  "Does the student qualify for sibling preference for Montessori or TSM?": "SiblingPreference",
  "Enter the DPSCD Student ID for 1 sibling who attends the desired school": "SiblingID2",
  "Select the sibling's school": "SiblingSchool2",
  "Review You Will Complete": "ReviewType",
  "Describe the grade entering": "GradeEntering",
  "Sibling Name(s)": "SiblingNames",
  "DPSCD ID(s)": "SiblingIDs",
  "Montessori 2-8 Eligibility": "Eligibility28",
  "Is the student eligible for Montessori admission in 2-8?": "MontEligibilityFlag",
  "Sibling applicant name(s)": "SiblingApplicantNames",
  "Submission IDs for all sibling applicants": "SiblingSubmissionIDs",
  "Are the siblings applying to the same schools?": "SiblingSchools",
  "Is your sibling finding different from the Initial Review?": "SiblingReviewDiscrepancy",
  "Is the student applying for grades 2-8?": "SiblingApplying28",
  "Is your prior experience finding different from the Initial Review?": "ExperienceReviewDiscrepancy",
  "DPSCD Student ID for 1 sibling attending Mont/TSM": "MontSiblingID",
  "Select the sibling's DPSCD school": "MontSiblingSchool",
  "Describe the discrepancy. Provide details.": "DiscrepancyDetails",
  "What grade is the student entering?": "gradeEntering",
  "Is the student applying to a Montessori school?": "applyingMontessori",
  "Is the student eligible for Sibling priority?": "siblingPriority",
  "Based on the documentation provided, does the student have one year of prior Montessori experience?": "experienceMontessori",
  "Briefly describe the documentation provided and reason for eligibility.": "documentation1",
  "Describe the documentation provided": "documentation2",
  "Did the submission satisfy all requirements to be moved to the GPA Recording stage?": "RequirementsSatisfied",
  "Relevant Notes": "Notes",
  "Single Response Question": "Round",
  "Was this GPA calculated accurately?": "Accurate",
  "Please enter notes on the issue(s) you encountered.": "Notes",
  "Select all statements that apply to the documents submitted": "Issues",
  "Relevant Notes - For Internal Use Only": "NotesInternal",
  "Describe issue with submitted document. (This note will be sent to parents.)": "IssuesOther",
  "Please include notes about your findings": "Notes",
  "What grade is the student going in to?": "GradeEntering",
  "Did the applicant provide a transcript?": "TranscriptProvided",
  "Please review the application and select the appropriate response.": "Completion",
  "Optional notes/observations": "Notes",
  "After reviewing all components, what is your decision on this student's admission? ": "Decision",
  "Did you interview the applicant and/or the applicant's family?": "Interview",
  "When did you conduct the interview?": "InterviewWhen",
  "Whom did you interview?": "InterviewWho",
  "After reviewing all components, what is your decision on this student's admission?": "Decision",
  "When do you want to admit this student?": "AdmissionsTerm",
  "What is missing from the application?": "MissingInfo",
  "What is student's enrollment status?": "enrollmentStatus",
  "What is Missing?": "missing",
  "Enrollment Notes ": "enrollmentNotes",
  "Enrollment Notes": "enrollmentNotes",
  "Is the student eligible for K?": "EligibleK",
  "Notes": "Notes",
  "Is the student eligible for their desired grade?": "EligibleDesiredGrade",
  "Is the student eligible for Pre-K?": "EligiblePreK",
  "Is this student currently enrolled at your school?": "CurrentlyEnrolled",
  "Is this student in good Academic standing at your school? ": "GoodAcademicStanding",
  "Is this student in good standing for Behavior at your school?": "GoodBehaviorStanding",
  "Does this student demonstrate good Attendance at your school?": "GoodAttendance",
  "Please enter any other information you think may be pertinent to another principal who is making an admission decision.": "AdditionalInfo",
  "Please elaborate": "Elaboration",
}